language: go

go:
  - 1.10.x
  - 1.11.x
  - master

stages:
  - lint
  - test
  - build

jobs:
  include:
    - stage: lint
      script:
        - go get -u golang.org/x/lint/golint
        - golint -set_exit_status
        - go vet -v
    - stage: test
      script:
        - go test -v
    - stage: build
      script:
        - go build

matrix:
  allow_failures:
    - go: master
  fast_finish: true
