name: GitHub CI
on: [pull_request, workflow_dispatch]
jobs:
  build-project:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Build the project (Todo)
      - name: Build Porject
        run: |
          go version 
          
      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: src/
